version: "3.3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgre_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
  elasticsearch:
    image: elasticsearch:8.11.3
    environment:
      ELASTIC_USERNAME: "admin"
      ELASTIC_PASSWORD: "password"
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      environment:
      xpack.security.enabled: false
    ports:
      - "9200:9200"
      - "9300:9300"
  neo4j:
    image: neo4j:5.14.0-enterprise
    hostname: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_logs_debug_level: DEBUG